language: node_js
node_js:
  - stable

branches:
  only:
    - deploy

before_script:
  - git config --global user.email "robot@overlord.industries"
  - git config --global user.name "Travis CI"
  - git remote rm origin
  - git remote add origin https://joehand:${GH_TOKEN}@github.com/datproject/docs.git

env:
  global:
    - secure: encrypted-github-token
    - secure: >-
        b5NkZvr5v6+ROP2fxPV2NkkoXd5WAcaghTJHWEPINGW7fmeiHg8Qz4vmQy7i/rulsbgtpmnHYmx89yiHR+HTaZTWxqoUe0Ju6D5SLEzBB2dYtFi3X9sTfr3wEkyX8xF+4IFT9Rkv+8TsSj/jAOk7t49Gq0fAWRZTcZOfWL4LTzCgVwQG6QGBoYT7LB2FrbdfyqlwCkKBu2bCtc0bMcBRAMbcFDPOHcK+yAZGh7vs9NE9C7b0DdZLyzeigZ0loRqCTVa7SMXbFwj2tjhmKBXgFFKykIxq/fppsr2+QVDvFbe6MeKZArKapTSIiiHv6LSW3Uqrsh6vpjnlJz/VFPP6H03AM4IxhDzG7qAeBaa3OxXi1GWl4/gBcf4TlYmBksSTYv3WGh36oIPVpRBNDSbJ3pcvOP6cfbUegub/8zn8uxlZJ+g+YZyqxAn8CIgIpVXjJRyVBaIg9wB5XkmDfQYWANtQtphbUQBjitGxEBcSnFmRyl2Cb/9fJ2bzS/l21gQ/DTTs4hhzxGrWK1uLOmXCYz4r1uswvE8yXVauJTqtssMtLEDzAld1Db+nSo1ALMxtrO6EBNy+7g+86Tkonz4J/dPsyJIXqoQVcTRFr+Xu/ThNs20JBWEGE6VxBLew1mIRBLGf0v+onTvWvyWUTtHXnomTJRA9fJRaVYTSBE/BhYs=

install:
  - npm install

deploy:
  provider: script
  script: npm run travis:update && npm run deploy
  skip_cleanup: true
