site_name: Dat project
theme: readthedocs
pages:
- Home: 'index.md'
- 'How Dat Works': 'how-dat-works.md'
- Meta:
  - 'Changelog': 'meta/changelog.md'
  - 'Collaborators': 'meta/collaborators.md'
extra_css: [extra.css]
